name: flutter_templete

description: "Flutter_Templete"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router : ^12.1.1 # route 설정 라이브러리
  flutter_screenutil: ^5.9.3 # 글자 크기를 기기 해상도에 맞게 자동 조정 해주는 라이브러리
  provider: ^6.1.1 # 상태 관리 라이브러리
  get_it: ^8.0.0 # 의존성 주입 라이브러리
  injectable: ^2.0.0 # 의존성 주입 설정을 자동화하는 라이브러리
  dio: ^5.4.0 # JSON 직렬화/역직렬화, 요청 취소 지원, 로깅, 헤더 관리, 인터셉터 지원 라이브러리,
  permission_handler: ^11.0.0 # 안드로이드 권한 검사 라이브러리
  hive: ^2.2.3 # 로컬에 Json 형태로 데이터 저장
  hive_flutter: ^1.1.0 # hive를 편하게 사용할 수 있게하는 라이브러리
  logger: ^2.0.2+1 # 로그 라이브러리
  flutter_svg: ^2.0.9 # svg 이용 라이브러리
  flutter_localization: ^0.2.0
  path: any
  flutter_html: ^3.0.0-beta.2 #html 파일 띄우기
  webview_flutter: ^4.10.0 #flutter에서 웹뷰 띄우기
  webview_flutter_android: ^4.3.2 #Android에서 웹뷰 띄우기



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator: ^2.0.0 # 코드 생성을 위한 패키지
  build_runner: ^2.0.0 #코드 생성을 위한 빌드 러너

flutter:
  uses-material-design: true
  assets: # 사진 추가
    - assets/images/logo.png
    - assets/icons/bold-clock.svg


    - assets/html/profile.html
    - assets/html/profile_one.html

  fonts: # 폰트 추가
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSansKR-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSansKR-ExtraBold.ttf
          weight: 200
        - asset: assets/fonts/NotoSansKR-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansKR-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansKR-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansKR-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansKR-ExtraBold.ttf
          weight: 800



